const fs = require('fs');
let code = fs.readFileSync('src/data/sapaWaliData.ts', 'utf8');

const regex = /export function getFullSapaWaliDataset\(\)[\s\S]*?return result;\n\}/;

const newCode = `export function getFullSapaWaliDataset(): SapaWaliRecord[] {
  const result: SapaWaliRecord[] = [...RAW_SAPA_WALI_DATA];
  let nextId = RAW_SAPA_WALI_DATA.length + 1;

  for (const ext of EXTENDED_NAMES) {
    if (result.length >= 109) break;
    const tempRecord: SapaWaliRecord = {
      id: nextId,
      no: nextId,
      nik: \`127\${Math.floor(100000000000 + Math.random() * 899999999999)}\`,
      namaWali: ext.nama,
      tanggalPermohonan: "2026-05-15",
      nomorPenetapan: ext.tipe === "Perwalian" ? "Penetapan Perwalian Resmi" : "Penetapan Pengampuan Resmi",
      tanggalPenetapan: "2026-04-10",
      namaPengadilan: "PN Medan",
      provinsi: "Sumatera Utara",
      kotaKab: "Medan",
      hubungan: ext.tipe === "Perwalian" ? "Ibu Kandung" : "Anak Kandung",
      alamat: "Alamat tersimpan di database",
      noHp: "0812" + Math.floor(10000000 + Math.random() * 90000000),
      namaAnak: ext.anak,
      tanggalLahirAnak: "2020-01-01",
      jenisWewenang: ext.tipe as "Perwalian" | "Pengampuan"
    };
    result.push(tempRecord);
    nextId++;
  }

  // Sort by date generated by getRecordWorkdayDates so that it's chronological
  result.sort((a, b) => {
    const total = WORKDAYS_LIST.length;
    const idxA = (a.no * 11 + 3) % total;
    const idxB = (b.no * 11 + 3) % total;
    if (idxA !== idxB) return idxA - idxB;
    // secondary sort by time
    const blastA = 8 * 60 + 15 + ((a.no * 7) % 60);
    const blastB = 8 * 60 + 15 + ((b.no * 7) % 60);
    return blastA - blastB;
  });

  return result;
}`;

code = code.replace(regex, newCode);
fs.writeFileSync('src/data/sapaWaliData.ts', code, 'utf8');
console.log('patched sort date successfully 2');
